#!/bin/bash
clear
read -p "Digite seu IP/Host: " $ip
sleep 2s
echo
read -p "Digite sua porta OpenVPN: " $openvpn_port
sleep 2s
echo
read -p "Digite seu Usuário openvpn: " $user
sleep 2s
echo
read -p "Digite sua Senha openvpn: " $pass
sleep 2s
echo
read -p "Digite seu Proxy: " $proxy
sleep 2s
echo
read -p "Digite sua Porta do Proxy: " $proxy_port
sleep 2s
echo
clear
echo client
dev tun
proto tcp
remote $ip $openvpn_port
http-proxy $proxy $proxy_port
#payload "C $ip:$openvpn_port[split][crlf]acl http/\n"
remote-cert-tls server
resolv-retry infinite
nobind
tun-mtu 1500
tun-mtu-extra 32
mssfix 1450
persist-key
persist-tun
<auth-user-pass>
$user
$pass
</auth-user-pass>
auth-nocache
comp-lzo
reneg-sec 0
verb 3
<ca>

